<?php

declare(strict_types=1);

namespace App\Services\Payment;

/**
 * Class PaymentResult
 *
 * Immutable value object representing the outcome of a payment transaction.
 *
 * Used by {@see \App\Services\Payment\CheckoutPaymentGateway} and other
 * payment gateways to encapsulate payment status, message, and transaction ID
 * in a consistent, type-safe structure.
 *
 * **Key Features:**
 * - Immutable: once created, properties cannot be changed.
 * - Provides static factories for success and failure cases.
 * - Standardized structure for all payment-related responses.
 *
 * @package App\Services\Payment
 */
final class PaymentResult
{
    /**
     * Indicates whether the payment was successful.
     *
     * @var bool
     */
    public bool $success;

    /**
     * Optional descriptive message about the transaction outcome.
     *
     * @var string|null
     */
    public ?string $message;

    /**
     * The unique identifier for the transaction, if available.
     *
     * @var string|null
     */
    public ?string $transactionId;

    /**
     * Create a new immutable payment result instance.
     *
     * @param bool $success
     *     Whether the payment succeeded.
     * @param string|null $message
     *     Optional status or error message.
     * @param string|null $transactionId
     *     Optional transaction reference (if available).
     */
    public function __construct(bool $success, ?string $message = null, ?string $transactionId = null)
    {
        $this->success = $success;
        $this->message = $message;
        $this->transactionId = $transactionId;
    }

    /**
     * Create a successful payment result instance.
     *
     * @param string|null $transactionId
     *     The transaction reference generated by the gateway.
     * @param string|null $message
     *     Optional success message.
     *
     * @return self
     *     Returns a new PaymentResult representing a successful transaction.
     */
    public static function success(?string $transactionId = null, ?string $message = null): self
    {
        return new self(true, $message, $transactionId);
    }

    /**
     * Create a failed payment result instance.
     *
     * @param string|null $message
     *     The reason for failure or error description.
     * @param string|null $transactionId
     *     Optional transaction reference (if available).
     *
     * @return self
     *     Returns a new PaymentResult representing a failed transaction.
     */
    public static function failure(?string $message = null, ?string $transactionId = null): self
    {
        return new self(false, $message, $transactionId);
    }
}
